# preload = ~/.dotfiles/wallpapers/pixel_akita_orca.jpg
# preload = ~/.dotfiles/wallpapers/pixel_nixos_penguin.jpg

# wallpaper =eDP-1,~/.dotfiles/wallpapers/pixel_akita_orca.jpg
# wallpaper =HDMI-A-1,~/.dotfiles/wallpapers/pixel_nixos_penguin.jpg
# wallpaper =DP-9,~/.dotfiles/wallpapers/pixel_nixos_penguin.jpg
# wallpaper =DP-1,~/.dotfiles/wallpapers/pixel_akita_orca.jpg
# wallpaper =DP-10,~/.dotfiles/wallpapers/pixel_akita_orca.jpg
# wallpaper =DP-2,~/.dotfiles/wallpapers/pixel_akita_orca.jpg


wallpaper {
    monitor = eDP-1
    path = ~/.dotfiles/wallpapers/pixel_akita_orca.jpg
    fit_mode = cover
}
wallpaper { 
    monitor = HDMI-A-1
    path = ~/.dotfiles/wallpapers/pixel_nixos_penguin.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-9
    path = ~/.dotfiles/wallpapers/pixel_nixos_penguin.jpg
    fit_mode = cover
}
wallpaper { 
    monitor = DP-1
    path = ~/.dotfiles/wallpapers/pixel_akita_orca.jpg
    fit_mode = cover
}
wallpaper { 
    monitor = DP-10
    path = ~/.dotfiles/wallpapers/pixel_akita_orca.jpg
    fit_mode = cover
}
wallpaper { 
    monitor = DP-2
    path = ~/.dotfiles/wallpapers/pixel_akita_orca.jpg
    fit_mode = cover
}
