exec = hyprctl setcursor catppuccin-mocha-mauve-cursors 24

env = HYPRCURSOR_THEME,catppuccin-mocha-mauve-cursors
env = XCURSOR_THEME,catppuccin-mocha-mauve-cursors

general {
	col.active_border = rgb(8764C7) rgb(dda16f) 45deg
}

