exec = hyprctl setcursor catppuccin-mocha-red-cursors 24

env = HYPRCURSOR_THEME,catppuccin-mocha-red-cursors
env = XCURSOR_THEME,catppuccin-mocha-red-cursors

general {
    col.active_border = rgb(fc50b4) rgb(7ac3ff) 45deg
}

